version: 0.{branch}.{build}

environment:
  matrix:
   - KETTLE_VERSION: 6.1.0.9-307
   - KETTLE_VERSION: 7.1.0.19-174

build_script:
- cmd: 'mvn -Dpentaho.kettle.version=%KETTLE_VERSION% package -B -V'

test_script:
- cmd: 'mvn -Dpentaho.kettle.version=%KETTLE_VERSION% -DskipTests=false test -B'


notifications:
- provider: Email
  to:
  - slawomir.chodnicki@gmail.com
  subject: AppVeyor build status changed
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true
cache:
  - '%USERPROFILE%\.m2 -> appveyor.yml'